services:
  kibana:
    image: kibana:8.7.1
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

  elasticsearch:
    image: elasticsearch:8.7.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  logstash:
    image: logstash:8.7.1
    ports:
      - "5001:5000"
      - "9600:9600"
    volumes:
      - ./configs/logstash/pipelines/springboot.conf:/usr/share/logstash/pipeline/springboot.conf

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./configs/prometheus:/etc/prometheus/
    hostname: prometheus
    command:
      - --config.file=/etc/prometheus/config.yml
    ports:
      - "9090:9090"

networks:
  elk:
    driver: bridge
